=== Fatima5322/Anti-fraud-system/JSONschema2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "MongoDB-документ антифрод-проверки",
  "description": "JSON Schema для валидации документа антифрод-проверки",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "_id",
    "check_id",
    "status",
    "risk_level",
    "rules_decision",
    "automatic_decision",
    "final_decision",
    "created_at",
    "completed_at",
    "transaction",
    "fraud_rules"
  ],
  "properties": {
    "_id": {
      "type": "string"
    },
    "check_id": {
      "type": "string",
      "format": "uuid"
    },
    "status": {
      "type": "string",
      "enum": [
        "IN_PROGRESS",
        "MANUAL_REVIEW",
        "COMPLETED"
      ]
    },
    "risk_level": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "LOW",
            "MEDIUM",
            "HIGH",
            "UNKNOWN"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "rules_decision": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "APPROVED",
            "REJECTED",
            "MANUAL_REVIEW"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "automatic_decision": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "APPROVED",
            "REJECTED",
            "MANUAL_REVIEW"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "final_decision": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "APPROVED",
            "REJECTED"
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "created_at": {
      "type": "string",
      "format": "date-time"
    },
    "completed_at": {
      "oneOf": [
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": "null"
        }
      ]
    },
    "transaction": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "transaction_id",
        "sender_account",
        "recipient_account",
        "amount",
        "currency",
        "transaction_date",
        "ip_address",
        "origin_country",
        "device_id",
        "payment_channel",
        "tariff"
      ],
      "properties": {
        "transaction_id": {
          "type": "string",
          "format": "uuid"
        },
        "sender_account": {
          "type": "string"
        },
        "recipient_account": {
          "type": "string"
        },
        "amount": {
          "type": "number",
          "format": "double",
          "minimum": 0.01
        },
        "currency": {
          "type": "string",
          "minLength": 3,
          "maxLength": 3
        },
        "transaction_date": {
          "type": "string",
          "format": "date-time"
        },
        "ip_address": {
          "type": "string"
        },
        "origin_country": {
          "type": "string",
          "minLength": 2,
          "maxLength": 2
        },
        "device_id": {
          "type": "string"
        },
        "payment_channel": {
          "type": "string",
          "enum": [
            "MOBILE_APP",
            "WEB"
          ]
        },
        "tariff": {
          "type": "string"
        }
      }
    },
    "manual_review": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "review_id",
        "mr_status",
        "comment",
        "final_decision",
        "created_at",
        "completed_at"
      ],
      "properties": {
        "review_id": {
          "type": "string",
          "format": "uuid"
        },
        "mr_status": {
          "type": "string",
          "enum": [
            "IN_PROGRESS",
            "COMPLETED"
          ]
        },
        "comment": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "final_decision": {
          "oneOf": [
            {
              "type": "string",
              "enum": [
                "APPROVED",
                "REJECTED"
              ]
            },
            {
              "type": "null"
            }
          ]
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "completed_at": {
          "oneOf": [
            {
              "type": "string",
              "format": "date-time"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "fraud_rules": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "_id",
          "rule_id",
          "rule_name",
          "rule_description",
          "is_active",
          "created_at",
          "updated_at"
        ],
        "properties": {
          "_id": {
            "type": "string"
          },
          "rule_id": {
            "type": "string",
            "format": "uuid"
          },
          "rule_name": {
            "type": "string"
          },
          "rule_description": {
            "type": "string"
          },
          "is_active": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  }
}

=== Fatima5322/Anti-fraud-system/JSONobject.json
{
  "_id": "6871c6d42e3d4c6c9c9a1001",
  "check_id": "7df76e95-9e5b-4aef-b09e-f7ab826afdf6",
  "status": "COMPLETED",
  "risk_level": "MEDIUM",
  "rules_decision": "MANUAL_REVIEW",
  "automatic_decision": "MANUAL_REVIEW",
  "final_decision": "APPROVED",
  "created_at": "2026-07-01T15:30:01Z",
  "completed_at": "2026-07-01T16:05:17Z",
  "transaction": {
    "transaction_id": "5a5cb1d2-38e5-4d39-b6a0-215dfe4e7138",
    "sender_account": "NL91ABNA0417164300",
    "recipient_account": "NL20INGB0001234567",
    "amount": 1500.50,
    "currency": "EUR",
    "transaction_date": "2026-07-01T15:30:00Z",
    "ip_address": "192.168.10.15",
    "origin_country": "NL",
    "device_id": "device-f3c91d88",
    "payment_channel": "MOBILE_APP",
    "tariff": "Premium"
  },
  "manual_review": {
    "review_id": "f44bdb95-5b34-4328-8d63-b37b44d5eaf4",
    "mr_status": "COMPLETED",
    "comment": null,
    "final_decision": "APPROVED",
    "created_at": "2026-07-01T15:30:08Z",
    "completed_at": "2026-07-01T16:05:17Z"
  },
  "fraud_rules": [
    {
      "_id": "5961c6d53e3d7c6c1c9a2002",
      "rule_id": "2b9fa56f-1980-4cf9-9dcb-91b89cbff6cb",
      "rule_name": "Крупная сумма",
      "rule_description": "Запускает дополнительную проверку при переводах на сумму свыше 100000 EUR",
      "is_active": true,
      "created_at": "2026-07-01T15:30:02Z",
      "updated_at": "2026-07-10T15:30:02Z"
    }
  ]
}
